---
title: "Project 1"
author: "Your Name Here"
format: html
self-contained: true
editor: source
---

```{r setup, echo = TRUE, warnings = FALSE, message = FALSE}
library(tidyverse)
library(gsheet)
```


**1. Members of the UWF basketball team decided to see if there was a difference in scoring on free throws during the first and second halves of games. Data was collected over thirteen games and is as follows:**

| 1st Half | 19 | 13 | 7 | 21 | 20 | 13 | 14 | 8 | 11 | 20 | 16 | 9 | 10 |
|----------|----|----|---|----|----|----|----|---|----|----|----|---|----|
| **2nd Half** | **17** | **9**  | **8** | **22** | **14** | **9** | **15** | **8** | **12** | **14** | **8**  | **8** | **10** |

**a. Find the appropriate summary statistics to summarize the data.**

**b. Perform the appropriate *t* test to determine if there is a difference in the number of free throws made during the first and second halves of games. Remember to typeset the hypothesis test results.**
    
**c. Perform the appropriate nonparametric test to determine if there is a difference in the number of free throws made during the first and second halves of games. Remember to typeset the hypothesis test results.**
    
**d. Construct the necessary graphs / hypothesis tests to assess the assumptions on the *t* test.**
    
**e. State the assumption(s) on the *t* test and provide your assessment based on results in part (d).**
    
**f. Based on your assessment in part (e), are you going to report the *t* test or the nonparametric test?**
    
**g. Write a brief paragraph describing the results of your analysis. Include summary statistics, results of your chosen hypothesis test from part (f), and a graph to help convey the results.**
    
**2. It is hypothesized that students in College Algebra skip class less often than students in General Chemistry I; both courses seat 90 students. Data on the total number of absences per section was collected for one fall semester, and is as follows:**

| General Chemistry I | 161 | 140 | 136 | 171 | 106 | 149 |
|---------------------|-----|-----|-----|-----|-----|-----|
| **College Algebra** | **158** | **132** | **135** | **185** | **106** | **150** |

**a. Find the appropriate summary statistics to summarize the data.**

**b. Perform the appropriate *t* test to determine if there are fewer absences in College Algebra. Remember to typeset the hypothesis test results.**
    
**c. Perform the appropriate nonparametric test to determine if there are fewer absences in College Algebra. Remember to typeset the hypothesis test results.**
    
**d. Construct the necessary graphs / hypothesis tests to assess the assumptions on the *t* test.**
    
**e. State the assumption(s) on the *t* test and provide your assessment based on results in part (d).**
    
**f. Based on your assessment in part (e), are you going to report the *t* test or the nonparametric test?**
    
**g. Write a brief paragraph describing the results of your analysis. Include summary statistics, results of your chosen hypothesis test from part (f), and a graph to help convey the results.**

    