---
title: "Project 2"
author: "Your Name Here"
format: html
self-contained: true
editor: source
---

```{r setup, echo = TRUE, warnings = FALSE, message = FALSE}
library(tidyverse)
library(gsheet)
data <- as_tibble(gsheet2tbl("https://docs.google.com/spreadsheets/d/1H3TP-2SBMGleriJLESOe1cdCjtSj2F76bUh5iBqC8tI/edit#gid=2142000894"))
```

**1. Consider a sample of data from the [Jackson Heart Study](https://www.jacksonheartstudy.org/). In this problem, we will be examining body mass index (*BMI*; kg/m<sup>2</sup>) as a function of health as categorized by physical activity (*PA3cat*; Ideal Health, Intermediate Health, and Poor Health).**

**a. Find the appropriate summary statistics to summarize the data.**

**b. Use ANOVA to determine if there is a difference in BMI between the three levels of health as categorized by physical activity. Test at the $\alpha=0.05$ level.**

**c. Use the Kruskal-Wallis to determine if there is a difference in BMI between the three levels of health as categorized by physical activity (*PA3cat*; Ideal Health, Intermediate Health, and Poor Health). Test at the $\alpha=0.05$ level.**

**d. State/explain the ANOVA assumptions and assess them. Remember to state your conclusion (that you either meet the ANOVA assumptions or you do not).**

**e. Based on your responses in part (d), which test's result are you going to present to the lead scientist at the JHS? (Hint: you will pick either (b) or (c)).**

**f. Perform the appropriate posthoc test to determine pairwise differences between the three groups. Test at the $\alpha=0.05$ level.**

**g. Write a brief paragraph describing the results of your analysis. Include summary statistics, results of your chosen hypothesis test from part (e), results of the posthoc test in part (f), and a graph to help convey the results.**

**2. Again, consider the sample of data from the JHS. In this problem, we will be examining systolic blood pressure (*sbp*; mmHg) as a function of health as categorized by body mass index (*BMI3cat*; Ideal Health, Intermediate Health, and Poor Health), smoking status (*everSmoker*; 0=never smoker, 1=former or current smoker), and the interaction between health as categorized by body mass index and smoking status.**

**a. Find the appropriate summary statistics to summarize the data.**

**b. Use ANOVA to determine if there is a difference in systolic blood pressure between health as categorized by body mass index, smoking status, and the interaction between health as categorized by body mass index and smoking status. Test at the $\alpha=0.05$ level. Remember to remove the interaction term if appropriate to do so.**

**c. Construct a profile plot to help explain results of part (b).**

**d. Use the appropriate posthoc test to determine differences in main effects or the interaction term, whichever is appropriate for the results in part (b). Test at the $\alpha=0.05$ level.**

**e. Write a brief paragraph describing the results of your analysis. Include summary statistics, results of the hypothesis testing in part (b), results of the posthoc test in part (d), and the profile plot in part (c) to help convey the results.**





















