---
title: "Two-Way ANOVA - Week 6, Lecture 1"
author: "Your Name Here"
format: html
self-contained: true
editor: source
---

## Q1:

**A large advertising firm specializes in creating television commercials for children's products. The firm wants to design a study to investigate factors that may affect the lengths of time a commercial is able to hold a child's attention. A preliminary study determines that two factors that may be important are the age of the child and the type of product being advertised. The firm wants to determine whether there were large differences in the mean length of time that the commercial is able to hold the child's attention depending on these two factors. If there proves to be a difference, the firm would then attempt to determine new types of commercials depending on the product and targeted age group.**

**Three age groups are used:**

-   **A**<sub>**1**</sub>**: 5-6 years,**
-   **A**<sub>**2**</sub>**: 7-8 years,**
-   **A**<sub>**3**</sub>**: 9-10 years**

**The types of products selected are:**

-   **P**<sub>**1**</sub>**: breakfast cereals,**
-   **P**<sub>**2**</sub>**: video games**

**A group of 30 children is recruited in each age group, and 10 are randomly assigned to watch a 60-second commercial for each of the two products. Researchers record their attention spans during the viewing of the commercial. The data are given here: [Google Sheet](https://docs.google.com/spreadsheets/d/16_HOSmIBDD9oYY1oBQ5Df6eFH9nT6GgO1UWcbMZNLUo/edit?usp=sharing).**

a.  Construct the two-way ANOVA table.

b.  Use the appropriate hypothesis test to show that the interaction between age and product is significant. Test at the $\alpha=0.05$ level.

## Q2:

**A horticulturalist at a large research institution designs a study to evaluate the effect on tomato yields of water loss due to transpiration. She decides to examine four levels of shading of the tomato plants at three stages of the tomato plant's development. The four levels of shading (0, 25%, 50%, and 75%) were selected to reduce the solar exposure of the plants. The shading remained in place for 20 days during the early, middle, and late phases of the tomato plants' growth. There were four plots of tomatoes randomly assigned to each of the combinations of shading and growth stage. At the end of the study, the yields per plot in pounds were recorded. The data are given here: [Google Sheet](https://docs.google.com/spreadsheets/d/1kUxXje3cTl_PZFQcg8FvESo34UuGNwm1GrKGc4HN0_A/edit?usp=sharing).**

a.  Construct the two-way ANOVA table.

b.  Use the appropriate hypothesis test to show that the interaction between shading and phase of growth is not significant. Test at the $\alpha=0.10$ level.

c.  Remove the interaction term and reconstruct the two-way ANOVA table.

d.  Use the appropriate hypothesis test to determine if there is a main effect of shading. Test at the $\alpha=0.10$ level.

e.  Use the appropriate hypothesis test to determine if there is a main effect of phase of growth. Test at the $\alpha=0.10$ level.
