---
title: "Two-Way ANOVA - Week 6, Lecture 2"
author: "Your Name Here"
format: html
self-contained: true
editor: source
---

## Q1:

**Recall the advertising data from the last activity; you showed that there was an interaction between age and product type.**

a. Construct the profile plot for this data.

b. (Challenge!) Perform Tukey's test to determine which treatment groups are significantly different. Test at the $\alpha=0.05$ level.

c. Write a short paragraph to explain your results to the advertising researchers.

## Q2:

**Recall the tomato data from the last activity; you showed that there was not an interaction between shading and phase of growth and that there was at least one main effect.**

a.  (Challenge!) Construct the profile plot for this data.

b. If there is a main effect of shading, perform Tukey's test to determine which levels of shading are significantly different. Test at the $\alpha=0.10$ level.

c.  If there is a main effect of phase of growth, perform Tukey's test to determine which phases of growth are significantly different. Test at the $\alpha=0.10$ level.

d. Write a short paragraph to explain your results to the horticulturist. 