---
title: "Simple Linear Regression - Week 9, Lecture 1"
author: "Your Name Here"
format: html
self-contained: true
editor: source
---

**An online retailer needs to manage the amount of time needed to select the ordered items and assemble them for shipping. In order to assess the amount of time (Time) his assemblers devote to this task, the retailer takes a random sample of 100 orders and records the number of items in each order (Noltems) and the time needed to assemble the shipment. The data are given here: [Google Sheet](https://docs.google.com/spreadsheets/d/1xAsE0KmspC0dP4Uuyym33uU1G8ahI6z7wPVwts7BTRM/edit?usp=sharing).**

1. Summarize the data using appropriate summary statistics.

2. Model the amount of time as a function of the number of items in the order.

3. Find the 95% confidence interval for $\beta_1$.

4. Use the appropriate hypothesis test to determine if the number of items in the order is a significant predictor of the amount of time to pick and ship the order. Test at the $\alpha=0.05$ level.

5. State and assess the assumptions of linear regression. Is our model valid?

6. Find Pearson's correlation between the amount of time and the number of items and the corresponding 95% confidence interval.

7. Find Spearman's correlation between the amount of time and the number of items and the corresponding 95% confidence interval.

8. State and assess the assumptions for Pearson's correlation. Is Pearson's correlation valid for this data?

9. Construct a visualization for the model. At the very least, you should have a scatterplot with a regression line overlaid.

