---
title: "Multiple Regression: Estimation and Inference - Week 9, Lecture 2"
author: "Your Name Here"
format: html
self-contained: true
editor: source
---

**A regional airline transfers passengers from small airports to a larger regional hub airport. The airline’s data analyst was assigned to estimate the revenue (in thousands of dollars) generated by each of the 22 small airports based on two variables: the distance from each airport (in miles) to the hub and the population (in hundreds) of the cities in which each of the 22 airports is located. The data are given here: [Google Sheet](https://docs.google.com/spreadsheets/d/10ZN0jMYdVsG2ucIJFSTquVRW916Jj-JmZIGQuqSQhy0/edit?usp=sharing).**

1. Summarize the data using appropriate summary statistics.

2. Construct the correlation matrix for revenue, distance, and population. 

3. Are any correlations in Q2 suspiciously high?

4. Model the revenue as a function of distance and population.

5. Provide appropriate interpretations for the model coefficients.

6. Find the 95% confidence interval for all $\beta_i$.

7. Use the appropriate hypothesis test to determine if distance is a significant predictor of revenue. Test at the $\alpha=0.05$ level.

8. Use the appropriate hypothesis test to determine if population is a significant predictor of revenue. Test at the $\alpha=0.05$ level.

9. Use the appropriate hypothesis test to determine if this is a significant regression line. Test at the $\alpha=0.05$ level.

10. Find the $R^2_{\text{adj}}$ value and provide an interpretation.

11. Construct a visualization for the model. At the very least, you should have a scatterplot with a regression line overlaid.