---
title: "Multiple Regression: Diagnostics - Week 10, Lecture 1"
author: "Your Name Here"
format: html
self-contained: true
editor: source
---

**Recall the airline data from last week; we modeled revenue as a function of distance and population. The data are given here: [Google Sheet](https://docs.google.com/spreadsheets/d/10ZN0jMYdVsG2ucIJFSTquVRW916Jj-JmZIGQuqSQhy0/edit?usp=sharing).**

1. Summarize your findings from last week. What was the resulting model, which were significant predictors of revenue (no formal hypothesis test needed - just state with appropriate evidence)? Also include the graph constructed to visualize the model.

2. Determine if there are outliers in this model. Be sure to count and list the observations that are outliers.

3. Determine if there are any influence and leverage points in this model. Be sure to count and list the observations that are considered influential and leverage.

4. Is there evidence of multicollinearity? 

5. Perform a sensitivity analysis: remove the data points identified as potential offenders in Q2 and Q3 and reconstruct the model. Be sure to state the resulting model.

6. Using the model in Q5, are there any significant predictors of revenue?

7. Reconstruct the data visualization from last week, but using the new model's results.

8. Put the graphs from last week and Q7 side by side (hint: use `ggpubr`).

9. Compare and contrast the modeling results and the graphs that are side by side in Q8.

10. Why do you think I assigned this particular dataset for analysis? What are you taking away from this assignment?